/// Canonical XML tag/attribute name mappings.
///
/// Ported from `schema_en.properties` and `schema_ja.properties` of the Java
/// original. Configuration files written with the English names are the
/// standard; Japanese-named files (classic Shimeji) are also accepted by
/// checking the root tag name.
library;

const Map<String, String> schemaEn = {
  'Mascot': 'Mascot',
  'ActionList': 'ActionList',
  'Action': 'Action',
  'ActionReference': 'ActionReference',
  'Name': 'Name',
  'Type': 'Type',
  'Embedded': 'Embedded',
  'Move': 'Move',
  'Stay': 'Stay',
  'Animate': 'Animate',
  'Sequence': 'Sequence',
  'Select': 'Select',
  'Class': 'Class',
  'Draggable': 'Draggable',
  'Affordance': 'Affordance',
  'BorderType': 'BorderType',
  'Ceiling': 'Ceiling',
  'Wall': 'Wall',
  'Floor': 'Floor',
  'BornX': 'BornX',
  'BornY': 'BornY',
  'BornBehaviour': 'BornBehavior',
  'BornMascot': 'BornMascot',
  'BornTransient': 'BornTransient',
  'BornInterval': 'BornInterval',
  'BornCount': 'BornCount',
  'Characteristics': 'Characteristics',
  'Breed': 'Breed',
  'Scan': 'Scan',
  'TargetBehaviour': 'TargetBehavior',
  'TargetLook': 'TargetLook',
  'TargetX': 'TargetX',
  'TargetY': 'TargetY',
  'VelocityParam': 'VelocityParam',
  'InitialVX': 'InitialVX',
  'InitialVY': 'InitialVY',
  'ResistanceX': 'RegistanceX',
  'ResistanceY': 'RegistanceY',
  'Gravity': 'Gravity',
  'IeOffsetX': 'IeOffsetX',
  'IeOffsetY': 'IeOffsetY',
  'OffsetX': 'OffsetX',
  'OffsetY': 'OffsetY',
  'OffsetType': 'OffsetType',
  'X': 'X',
  'Y': 'Y',
  'LookRight': 'LookRight',
  'TransformBehaviour': 'TransformBehavior',
  'TransformMascot': 'TransformMascot',
  'Loop': 'Loop',
  'VelocityX': 'VelocityX',
  'VelocityY': 'VelocityY',
  'FootX': 'FootX',
  'FootDX': 'FootDX',
  'Animation': 'Animation',
  'Condition': 'Condition',
  'IsTurn': 'IsTurn',
  'Pose': 'Pose',
  'Image': 'Image',
  'ImageRight': 'ImageRight',
  'ImageAnchor': 'ImageAnchor',
  'Velocity': 'Velocity',
  'Duration': 'Duration',
  'Sound': 'Sound',
  'Volume': 'Volume',
  'Hotspot': 'Hotspot',
  'Shape': 'Shape',
  'Origin': 'Origin',
  'Size': 'Size',
  'Behaviour': 'Behavior',
  'BehaviourList': 'BehaviorList',
  'BehaviourReference': 'BehaviorReference',
  'Frequency': 'Frequency',
  'Hidden': 'Hidden',
  'Toggleable': 'Toggleable',
  'NextBehaviourList': 'NextBehaviorList',
  'Add': 'Add',
  'ChaseMouse': 'ChaseMouse',
  'Fall': 'Fall',
  'Dragged': 'Dragged',
  'Thrown': 'Thrown',
  'Constant': 'Constant',
  'Value': 'Value',
  'Information': 'Information',
  'PreviewImage': 'PreviewImage',
  'SplashImage': 'SplashImage',
  'Artist': 'Artist',
  'Scripter': 'Scripter',
  'Commissioner': 'Commissioner',
  'Support': 'Support',
  'URL': 'URL',
};

const Map<String, String> schemaJa = {
  'Mascot': 'マスコット',
  'ActionList': '動作リスト',
  'Action': '動作',
  'ActionReference': '動作参照',
  'Name': '名前',
  'Type': '種類',
  'Embedded': '組み込み',
  'Move': '移動',
  'Stay': '静止',
  'Animate': '固定',
  'Sequence': '複合',
  'Select': '選択',
  'Class': 'クラス',
  'BorderType': '枠',
  'Ceiling': '天井',
  'Wall': '壁',
  'Floor': '地面',
  'BornX': '生まれる場所X',
  'BornY': '生まれる場所Y',
  'BornBehaviour': '生まれた時の行動',
  'TargetX': '目的地X',
  'TargetY': '目的地Y',
  'VelocityParam': '速度',
  'InitialVX': '初速X',
  'InitialVY': '初速Y',
  'ResistanceX': '空気抵抗X',
  'ResistanceY': '空気抵抗Y',
  'Gravity': '重力',
  'IeOffsetX': 'IEの端X',
  'IeOffsetY': 'IEの端Y',
  'OffsetX': '端X',
  'OffsetY': '端Y',
  'X': 'X',
  'Y': 'Y',
  'LookRight': '右向き',
  'Loop': '繰り返し',
  'FootX': 'footX',
  'Animation': 'アニメーション',
  'Condition': '条件',
  'Pose': 'ポーズ',
  'Image': '画像',
  'ImageAnchor': '基準座標',
  'Velocity': '移動速度',
  'Duration': '長さ',
  'BehaviourList': '行動リスト',
  'Behaviour': '行動',
  'BehaviourReference': '行動参照',
  'Frequency': '精度',
  'NextBehaviourList': '次の行動',
  'Add': '追加',
  'Constant': '定数',
  'Value': '値',
};

/// The schema in effect for one configuration file.
class Schema {
  final Map<String, String> _map;
  const Schema(this._map);

  static const Schema en = Schema(schemaEn);
  static const Schema ja = Schema(schemaJa);

  String get(String key) => _map[key] ?? schemaEn[key] ?? key;
  bool get isJapanese => identical(_map, schemaJa);
}
